# frozen_string_literal: true

# NFDI4Objects Knowledge Graph TTL Aggregator
# ============================================
# Dieses Plugin aggregiert alle generierten TTL-Dateien aus _site
# zu einer einzigen nfdi4objects.ttl Datei für SPARQL-Abfragen.
#
# Das Plugin läuft NACH der Site-Generierung (Jekyll::Hooks :site, :post_write)
# und sammelt alle *.ttl Dateien ein.

module Jekyll
  module N4O
    class TTLAggregator
      NAMESPACES = <<~TTL
        @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
        @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
        @prefix owl: <http://www.w3.org/2002/07/owl#> .
        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
        @prefix skos: <http://www.w3.org/2004/02/skos/core#> .
        @prefix dcterms: <http://purl.org/dc/terms/> .
        @prefix foaf: <http://xmlns.com/foaf/0.1/> .
        @prefix geosparql: <http://www.opengis.net/ont/geosparql#> .
        @prefix locn: <http://www.w3.org/ns/locn#> .
        @prefix vcard: <http://www.w3.org/2006/vcard/ns#> .
        @prefix schema: <http://schema.org/> .
        @prefix sdo: <https://schema.org/> .
        @prefix nfdicore: <https://nfdi.fiz-karlsruhe.de/ontology#> .
        @prefix n4o: <https://nfdi4objects.net/ontology#> .

      TTL

      def initialize(site)
        @site = site
      end

      def aggregate
        Jekyll.logger.info "N4O TTL Aggregator:", "Starting aggregation..."

        site_dir = @site.dest
        ttl_files = Dir.glob(File.join(site_dir, "**", "*.ttl"))

        if ttl_files.empty?
          Jekyll.logger.warn "N4O TTL Aggregator:", "No TTL files found in #{site_dir}"
          return
        end

        Jekyll.logger.info "N4O TTL Aggregator:", "Found #{ttl_files.size} TTL files"

        aggregated_content = build_aggregated_ttl(ttl_files)
        output_path = File.join(site_dir, "nfdi4objects.ttl")

        File.write(output_path, aggregated_content)

        Jekyll.logger.info "N4O TTL Aggregator:", "✓ Created #{output_path} (#{aggregated_content.bytesize} bytes)"
      end

      private

      def build_aggregated_ttl(ttl_files)
        content = []
        content << "# NFDI4Objects Knowledge Graph"
        content << "# Aggregated TTL file generated by Jekyll"
        content << "# Generated at: #{Time.now.utc.iso8601}"
        content << "# Total files: #{ttl_files.size}"
        content << ""
        content << NAMESPACES
        content << ""

        ttl_files.each do |file|
          relative_path = file.sub(@site.dest + File::SEPARATOR, "")

          begin
            file_content = File.read(file, encoding: "UTF-8")

            # Remove namespace declarations from individual files
            # (they are already in the aggregated header)
            cleaned_content = remove_namespace_declarations(file_content)

            next if cleaned_content.strip.empty?

            content << "# Source: #{relative_path}"
            content << cleaned_content
            content << ""
          rescue StandardError => e
            Jekyll.logger.warn "N4O TTL Aggregator:", "Error reading #{relative_path}: #{e.message}"
          end
        end

        content.join("\n")
      end

      def remove_namespace_declarations(content)
        # Remove @prefix lines
        lines = content.lines.reject { |line| line.strip.start_with?("@prefix") }

        # Remove empty lines at the beginning
        lines = lines.drop_while { |line| line.strip.empty? }

        lines.join
      end
    end
  end
end

# Hook into Jekyll's post-write phase
Jekyll::Hooks.register :site, :post_write do |site|
  aggregator = Jekyll::N4O::TTLAggregator.new(site)
  aggregator.aggregate
end
